version: '3.7'

services:

  pay-checkout-backend:
    image: shajalahamedcse/pay-checkout-backend:0.0.2
    ports:
      - 5000:8000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.server.config.DevelopmentConfig
      - POSTGRES_SERVER_NAME=checkout-db
      - POSTGRES_SERVER_PORT=5432
      - POSTGRES_USER_NAME=postgres
      - POSTGRES_USER_PASS=postgres
    depends_on:
      - checkout-db

  checkout-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkout
    #   # POSTGRES_DB: ${POSTGRES_DB}
    #   # POSTGRES_USER: ${POSTGRES_USER}
    #   # POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
    #   # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  client:
    image: shajalahamedcse/pay-checkout-front:0.0.2
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - pay-checkout-backend