"""empty message

Revision ID: 20335c2edd73
Revises: 5cf2707f3d21
Create Date: 2020-10-10 18:06:07.344488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20335c2edd73'
down_revision = '5cf2707f3d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_details', sa.Column('target_product_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_details', 'target_product_id')
    # ### end Alembic commands ###
