"""empty message

Revision ID: 31d90a0b565c
Revises: c4f527cdd677
Create Date: 2020-10-10 12:43:38.138222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d90a0b565c'
down_revision = 'c4f527cdd677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promo_code', sa.String(length=255), nullable=False),
    sa.Column('is_flat', sa.Boolean(), nullable=False),
    sa.Column('discount_type', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promos')
    # ### end Alembic commands ###
