"""empty message

Revision ID: 5cf2707f3d21
Revises: 99c760e317ef
Create Date: 2020-10-10 15:43:52.672427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf2707f3d21'
down_revision = '99c760e317ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promos', sa.Column('valid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promos', 'valid')
    # ### end Alembic commands ###
