"""empty message

Revision ID: 99c760e317ef
Revises: ccd671094ac7
Create Date: 2020-10-10 14:12:43.923507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c760e317ef'
down_revision = 'ccd671094ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promos', sa.Column('least_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promos', 'least_amount')
    # ### end Alembic commands ###
